name: RiskModelDemo
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip=23.1.2
  - pandas=1.4.3
  - scikit-learn=0.24
  - pyathena
  - s3fs
  - matplotlib
  - pip:
    - catboost==1.0.5