name: catboost_poetry
channels:
  - defaults
  - conda-forge
  - huggingface
dependencies:
  - python=3.11
  - urllib3==1.26
  - pip
  - pytorch
  - catboost
  - pandas=2.2.2
  - numpy<2
  - transformers
  - accelerate
  - einops
  - xformers
  - poetry
  - scikit-learn